version: '3.2'
services:
  my-prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=debug'
    ports:
      # Map port 9090 inside the container to port 19090 on the host
      - 19090:9090

  my-app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:8000
      - 8123:8123
